device_alternate.hpp expects GPU member function declaration in class:
device_alternate.hpp:15:36: error: no ‘void caffe::SplitLayer<Dtype>::Forward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’ member function declared in class